// Generated by Selenium IDe
package testng;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test3() {
    driver.get("https://www.google.com/search?q=car&sca_esv=596768218&sxsrf=ACQVn0-hY37vtY98M1omkmvv0MZZcuABYw%3A1704782441150&source=hp&ei=aeqcZej4Bruk2roPxbK28AM&iflsig=ANes7DEAAAAAZZz4efdnRdTQ883Q-_3E2nTOg024pRQ8&ved=0ahUKEwio0cm-2c-DAxU7klYBHUWZDT4Q4dUDCAo&uact=5&oq=car&gs_lp=Egdnd3Mtd2l6IgNjYXIyChAjGIAEGIoFGCcyChAjGIAEGIoFGCcyChAuGEMYgAQYigUyChAAGIAEGIoFGEMyChAuGIAEGIoFGEMyChAuGIAEGIoFGEMyChAuGIAEGIoFGEMyEBAuGIAEGIoFGEMYxwEY0QMyChAAGIAEGIoFGEMyChAuGIAEGIoFGENIrUFQAFjWBXAAeACQAQCYAW2gAb0CqgEDMC4zuAEDyAEA-AEBwgIEECMYJ8ICCxAuGIAEGLEDGIMB&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(700, 576));
    driver.findElement(By.cssSelector("#rso > .MjjYud:nth-child(1) .notranslate:nth-child(3) .VuuXrf:nth-child(1)")).click();
  }
}
